export interface ScaffoldTemplateInput {
  pluginName: string;
  packageName: string;
  description: string;
}

function normalizePackageName(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function normalizeClassName(value: string) {
  return value
    .trim()
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
}

export function createScaffoldTemplate(input: ScaffoldTemplateInput) {
  const className = normalizeClassName(input.pluginName) || "PaperclipPlugin";
  const packageName = normalizePackageName(input.packageName);

  return [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: packageName,
          private: true,
          type: "module",
          version: "0.1.0",
          scripts: {
            build: "tsc -p tsconfig.json",
          },
        },
        null,
        2,
      ),
    },
    {
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "NodeNext",
            moduleResolution: "NodeNext",
            rootDir: "src",
            outDir: "dist",
            strict: false,
            skipLibCheck: true,
            types: ["node"],
          },
          include: ["src/**/*.ts"],
        },
        null,
        2,
      ),
    },
    {
      path: "src/index.ts",
      content: [
        'import { createPluginManifest, createWorkerConfig, definePlugin } from "../../sdk/src/index.js";',
        "",
        `export const ${className}Plugin = definePlugin({`,
        "  manifest: createPluginManifest({",
        `    id: "${packageName}",`,
        `    name: "${input.pluginName}",`,
        `    description: ${JSON.stringify(input.description)},`,
        '    version: "0.1.0",',
        '    entrypoint: "./worker.js",',
        '    worker: createWorkerConfig("node"),',
        "  }),",
        "  async run(input) {",
        "    return {",
        "      message: `run ${JSON.stringify(input)}`," ,
        "    };",
        "  },",
        "});",
        "",
        `export const plugin = ${className}Plugin;`,
        "",
      ].join("\n"),
    },
    {
      path: "src/worker.ts",
      content: [
        'import { startPluginWorker } from "../../sdk/src/index.js";',
        'import { plugin } from "./index.js";',
        "",
        "// The actual transport is host-specific; this file is the worker entry placeholder.",
        "export function registerWorker(transport: Parameters<typeof startPluginWorker>[0]) {",
        "  return startPluginWorker(transport, plugin);",
        "}",
        "",
      ].join("\n"),
    },
    {
      path: "README.md",
      content: [
        `# ${input.pluginName}`,
        "",
        input.description,
        "",
        "Generated by the Paperclip-style plugin scaffold.",
      ].join("\n"),
    },
  ];
}
