/**
 * Venice Live Inference — Real API Integration
 *
 * Replaces the mock step execution in private-reasoning.ts with
 * actual Venice API calls through the VeniceClient proxy.
 *
 * Each autonomous loop step (discover, plan, execute, verify) now
 * makes a real LLM inference call to Venice, captures the private
 * reasoning content, and returns structured output that flows
 * through the existing redaction pipeline.
 *
 * The private reasoning is generated by the Venice model and stored
 * in `venice_reasoning` fields — the redactPrivateReasoning() utility
 * strips these before they reach operator-visible logs.
 *
 * Fulfills: VAL-VENICE-001 (live private cognition)
 */

import { VeniceClient } from "./client";
import { VENICE_DEFAULT_MODEL } from "./config";
import type { StepResult } from "@/lib/agent-loop/types";
import type { ChatMessage } from "./types";
import { logExecution } from "@/lib/erc8004/execution-log";

/* ================================================================
   Types
   ================================================================ */

/** Input context for a Venice live inference step */
export interface VeniceLiveStepInput {
  /** The task description */
  task: string;
  /** The Venice model to use */
  veniceModel?: string;
  /** Agent name for context */
  agentName: string;
  /** Agent role for context */
  agentRole: string;
  /** The underlying adapter type */
  adapterType: string;
  /** Previous step results for context */
  previousSteps?: StepResult[];
  /** Company ID for evidence recording */
  companyId?: string;
  /** Agent ID for evidence recording */
  agentId?: string;
  /** Run ID for evidence recording */
  runId?: string;
  /** Custom system prompt override */
  systemPrompt?: string;
  /** Temperature (0-2) */
  temperature?: number;
  /** Max tokens */
  maxTokens?: number;
}

/** Result of a Venice live inference step */
export interface VeniceLiveStepResult {
  /** Step output data (includes venice_reasoning for redaction) */
  data: Record<string, unknown>;
  /** Whether the inference call succeeded */
  success: boolean;
  /** Token usage from the inference */
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
  /** Error if failed */
  error?: string;
}

/* ================================================================
   System Prompts per Step
   ================================================================ */

const STEP_SYSTEM_PROMPTS: Record<string, string> = {
  discover: `You are an autonomous AI agent performing task discovery and analysis.
Analyze the given task and determine:
- Complexity level (low/medium/high)
- Estimated number of sub-steps needed
- Whether human approval is required
- Key capabilities needed
Respond as JSON with fields: complexity, estimatedSteps, requiresApproval, capabilities, analysis.`,

  plan: `You are an autonomous AI agent creating an execution plan.
Given the task and discovery results, create a detailed execution plan with:
- Ordered list of subtasks
- Dependencies between subtasks
- Estimated effort for each
- Risk factors
Respond as JSON with fields: subtasks (array of {id, description, effort, dependencies}), risks, totalEstimate.`,

  execute: `You are an autonomous AI agent executing a task plan.
Given the task and plan, execute each subtask and report results.
For each subtask, provide:
- Status (completed/failed/skipped)
- Output or result
- Any issues encountered
Respond as JSON with fields: completedSubtasks (array of {id, status, result, issues}), summary.`,

  verify: `You are an autonomous AI agent verifying execution results.
Given the task, plan, and execution results, verify:
- All subtasks completed successfully
- Output quality meets requirements
- No security or safety issues
- Results are consistent and correct
Respond as JSON with fields: verified (boolean), issues (array), qualityScore (0-100), recommendations.`,
};

/* ================================================================
   Venice Live Step Execution
   ================================================================ */

/**
 * Execute a single autonomous loop step with a REAL Venice API call.
 *
 * This replaces the mock `executeVeniceStep()` with actual LLM inference.
 * The Venice model generates private reasoning which is captured in
 * `venice_reasoning` and `private_reasoning_content` fields for the
 * existing redaction pipeline.
 */
export async function executeVeniceLiveStep(
  step: string,
  input: VeniceLiveStepInput,
): Promise<VeniceLiveStepResult> {
  const model = input.veniceModel ?? VENICE_DEFAULT_MODEL;
  const client = new VeniceClient({ model });

  const baseMetadata = {
    veniceRouted: true,
    veniceModel: model,
    privateCognitionEnabled: true,
    adapterType: input.adapterType,
    liveInference: true,
  };

  try {
    // 1. Build messages for this step
    const messages = buildStepMessages(step, input);

    // 2. Call Venice API
    const response = await client.chatCompletion(messages, {
      temperature: input.temperature ?? 0.7,
      max_tokens: input.maxTokens ?? 4096,
    });

    // 3. Extract response content
    const rawContent = response.choices?.[0]?.message?.content ?? "";
    const usage = response.usage;

    // 4. Parse structured output (Venice returns JSON when prompted)
    let parsedOutput: Record<string, unknown>;
    try {
      parsedOutput = JSON.parse(rawContent);
    } catch {
      // If not valid JSON, wrap as text output
      parsedOutput = { rawOutput: rawContent };
    }

    // 5. Build result with private reasoning fields
    const stepData: Record<string, unknown> = {
      ...baseMetadata,
      ...parsedOutput,
      // Private reasoning — will be redacted by redactPrivateReasoning()
      venice_reasoning: rawContent,
      private_reasoning_content: `Venice ${model} ${step} step: ${rawContent.slice(0, 500)}`,
      veniceInference: {
        model,
        step,
        completedAt: new Date().toISOString(),
        tokensUsed: usage?.total_tokens ?? 0,
        finishReason: response.choices?.[0]?.finish_reason ?? "unknown",
      },
    };

    // 6. Record evidence
    if (input.companyId && input.agentId) {
      await logExecution(
        input.agentId,
        input.companyId,
        input.runId ?? null,
        "output",
        {
          action: `venice_live_${step}`,
          integration: "venice",
          model,
          step,
          tokensUsed: usage?.total_tokens ?? 0,
          estimatedCost: estimateVeniceCost(usage?.total_tokens ?? 0, model),
          // Note: actual reasoning content is logged but will be
          // redacted in any operator-facing export
          venice_reasoning: rawContent.slice(0, 200) + "...",
        },
      );
    }

    return {
      data: stepData,
      success: true,
      usage: usage
        ? {
            promptTokens: usage.prompt_tokens ?? 0,
            completionTokens: usage.completion_tokens ?? 0,
            totalTokens: usage.total_tokens ?? 0,
          }
        : undefined,
    };
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);

    // Record failure evidence
    if (input.companyId && input.agentId) {
      await logExecution(
        input.agentId,
        input.companyId,
        input.runId ?? null,
        "failure",
        {
          action: `venice_live_${step}_failed`,
          integration: "venice",
          model,
          step,
          error,
        },
      );
    }

    // Return graceful failure with metadata
    return {
      data: {
        ...baseMetadata,
        error,
        step,
        venice_reasoning: `Venice ${model} ${step} step failed: ${error}`,
      },
      success: false,
      error,
    };
  }
}

/* ================================================================
   Message Builders
   ================================================================ */

/**
 * Build the chat messages for a specific step.
 */
function buildStepMessages(
  step: string,
  input: VeniceLiveStepInput,
): ChatMessage[] {
  const systemPrompt =
    input.systemPrompt ?? STEP_SYSTEM_PROMPTS[step] ?? STEP_SYSTEM_PROMPTS.discover;

  const messages: ChatMessage[] = [
    { role: "system", content: systemPrompt },
    {
      role: "user",
      content: buildStepUserMessage(step, input),
    },
  ];

  return messages;
}

/**
 * Build the user message for a specific step, incorporating
 * previous step results for context continuity.
 */
function buildStepUserMessage(
  step: string,
  input: VeniceLiveStepInput,
): string {
  const context = [
    `Agent: ${input.agentName} (${input.agentRole})`,
    `Adapter: ${input.adapterType}`,
    `Task: ${input.task}`,
  ];

  // Add previous step context
  if (input.previousSteps?.length) {
    context.push("\n--- Previous Step Results ---");
    for (const prev of input.previousSteps) {
      const summary =
        typeof prev.data === "object"
          ? JSON.stringify(prev.data, null, 2).slice(0, 1000)
          : String(prev.data);
      context.push(`\n[${prev.step}] (${prev.status}):\n${summary}`);
    }
  }

  switch (step) {
    case "discover":
      context.push("\nAnalyze this task and provide a discovery assessment.");
      break;
    case "plan":
      context.push("\nCreate a detailed execution plan based on the discovery.");
      break;
    case "execute":
      context.push("\nExecute the plan and report results for each subtask.");
      break;
    case "verify":
      context.push("\nVerify the execution results and assess quality.");
      break;
  }

  return context.join("\n");
}

/* ================================================================
   Cost Estimation
   ================================================================ */

/**
 * Estimate Venice inference cost based on token usage.
 * Venice pricing varies by model tier.
 */
function estimateVeniceCost(totalTokens: number, model: string): string {
  // Venice pricing tiers (approximate, per 1k tokens)
  const PRICING: Record<string, number> = {
    "llama-3.3-70b": 0.002,
    "deepseek-r1-671b": 0.005,
    "qwen-2.5-vl-72b": 0.003,
  };

  const pricePerKToken = PRICING[model] ?? 0.002;
  const cost = (totalTokens / 1000) * pricePerKToken;
  return cost.toFixed(6);
}

/* ================================================================
   Full Loop Execution
   ================================================================ */

/**
 * Execute all four autonomous loop steps through Venice live inference.
 *
 * Runs discover → plan → execute → verify sequentially, passing
 * each step's output as context to the next.
 */
export async function executeVeniceLiveLoop(
  input: VeniceLiveStepInput,
): Promise<{
  steps: Array<{ step: string; result: VeniceLiveStepResult }>;
  success: boolean;
  totalTokens: number;
  error?: string;
}> {
  const steps: Array<{ step: string; result: VeniceLiveStepResult }> = [];
  const previousSteps: StepResult[] = [];
  let totalTokens = 0;

  for (const stepName of ["discover", "plan", "execute", "verify"]) {
    const result = await executeVeniceLiveStep(stepName, {
      ...input,
      previousSteps: [...previousSteps],
    });

    steps.push({ step: stepName, result });
    totalTokens += result.usage?.totalTokens ?? 0;

    // Build context for next step
    previousSteps.push({
      step: stepName,
      status: result.success ? "completed" : "failed",
      data: result.data,
    });

    // Stop if a step fails critically
    if (!result.success) {
      return {
        steps,
        success: false,
        totalTokens,
        error: `Step '${stepName}' failed: ${result.error}`,
      };
    }
  }

  return {
    steps,
    success: true,
    totalTokens,
  };
}
