import type { AgencySnapshot } from "./domain";

const now = new Date();
const minutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60_000).toISOString();

export const DEMO_SNAPSHOT: AgencySnapshot = {
  company: {
    id: "company-acme",
    slug: "acme-delegation",
    name: "Acme Delegation",
    companyType: "Autonomous product company",
    description: "A Supabase-backed AI agency cockpit with live operators, issue flows, and approvals.",
    brief:
      "Coordinate CEO and engineering work, keep approvals visible, and ship through the Delegation office with a dark control-plane shell.",
    brandColor: "#3b82f6",
    createdAt: minutesAgo(240),
    updatedAt: minutesAgo(3),
  },
  agents: [
    {
      id: "agent-ceo",
      companyId: "company-acme",
      name: "CEO",
      role: "ceo",
      title: "CEO",
      adapterType: "claude_local",
      status: "pending_approval",
      capabilities: "Strategy, planning, delegation, approval routing",
      reportsTo: null,
      seatIndex: 1,
      createdAt: minutesAgo(240),
      updatedAt: minutesAgo(4),
    },
    {
      id: "agent-founding-engineer",
      companyId: "company-acme",
      name: "Founding Engineer",
      role: "founding_engineer",
      title: "Founding Engineer",
      adapterType: "codex_local",
      status: "running",
      capabilities: "React, Supabase, Vite, full-stack shipping",
      reportsTo: "agent-ceo",
      seatIndex: 2,
      createdAt: minutesAgo(220),
      updatedAt: minutesAgo(2),
    },
  ],
  projects: [
    {
      id: "project-cockpit",
      companyId: "company-acme",
      name: "Agency Cockpit",
      summary: "Merge the Delegation 3D office into a Supabase/Lovable host.",
      status: "active",
      priority: "high",
      createdAt: minutesAgo(240),
      updatedAt: minutesAgo(2),
    },
  ],
  goals: [
    {
      id: "goal-launch",
      companyId: "company-acme",
      title: "Launch the merged cockpit",
      summary: "Ship the dark cockpit shell, scene runtime, and Supabase-ready data model.",
      status: "active",
      ownerAgentId: "agent-ceo",
      createdAt: minutesAgo(200),
      updatedAt: minutesAgo(6),
    },
  ],
  issues: [
    {
      id: "issue-ceo-heartbeat",
      companyId: "company-acme",
      projectId: "project-cockpit",
      assigneeAgentId: "agent-ceo",
      identifier: "ACM-1",
      title: "Create your CEO HEARTBEAT.md",
      description: "Draft the company heartbeat, define priorities, and route the first approval.",
      status: "blocked",
      priority: "medium",
      createdAt: minutesAgo(40),
      updatedAt: minutesAgo(29),
    },
    {
      id: "issue-shell",
      companyId: "company-acme",
      projectId: "project-cockpit",
      assigneeAgentId: "agent-founding-engineer",
      identifier: "ACM-2",
      title: "Wire the dark shell into Lovable",
      description: "Bring the cockpit scene and left nav into the existing Vite app without breaking package-lock ownership.",
      status: "in_progress",
      priority: "high",
      createdAt: minutesAgo(33),
      updatedAt: minutesAgo(2),
    },
  ],
  approvals: [
    {
      id: "approval-ceo-heartbeat",
      companyId: "company-acme",
      issueId: "issue-ceo-heartbeat",
      requestedByAgentId: "agent-ceo",
      status: "pending",
      summary: "Confirm the CEO heartbeat structure before execution continues.",
      createdAt: minutesAgo(29),
      resolvedAt: null,
    },
  ],
  runs: [
    {
      id: "run-engineer-1",
      companyId: "company-acme",
      issueId: "issue-shell",
      agentId: "agent-founding-engineer",
      status: "running",
      summary: "Applying cockpit shell and scene integration into the Lovable app.",
      stdoutExcerpt:
        "Mapped the Delegation scene runtime, adjusted the dark cockpit shell, and aligned the host routes with the new sidebar.",
      stderrExcerpt: null,
      error: null,
      totalInputTokens: 12800,
      totalOutputTokens: 4200,
      totalCachedInputTokens: 3100,
      totalCostUsd: 0.47,
      createdAt: minutesAgo(10),
      finishedAt: null,
    },
    {
      id: "run-ceo-1",
      companyId: "company-acme",
      issueId: "issue-ceo-heartbeat",
      agentId: "agent-ceo",
      status: "failed",
      summary: "Blocked on approval before continuing the company heartbeat.",
      stdoutExcerpt: "Prepared the first heartbeat outline and paused for board approval.",
      stderrExcerpt: null,
      error: "Awaiting approval response.",
      totalInputTokens: 7600,
      totalOutputTokens: 1800,
      totalCachedInputTokens: 900,
      totalCostUsd: 0.19,
      createdAt: minutesAgo(31),
      finishedAt: minutesAgo(29),
    },
  ],
  activity: [
    {
      id: "activity-1",
      companyId: "company-acme",
      agentId: "agent-ceo",
      issueId: "issue-ceo-heartbeat",
      action: "approval.requested",
      details: "Requested approval for the CEO heartbeat outline.",
      createdAt: minutesAgo(29),
    },
    {
      id: "activity-2",
      companyId: "company-acme",
      agentId: "agent-founding-engineer",
      issueId: "issue-shell",
      action: "run.started",
      details: "Started implementation for the Lovable cockpit shell.",
      createdAt: minutesAgo(10),
    },
  ],
  source: "demo",
  sourceMessage:
    "Showing demo data until the Supabase schema is applied or the project is populated.",
};
