"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateExecutionWorkspaceSchema = exports.issueWorkProductReviewStateSchema = exports.issueWorkProductStatusSchema = exports.issueWorkProductTypeSchema = exports.updateIssueWorkProductSchema = exports.createIssueWorkProductSchema = exports.upsertIssueDocumentSchema = exports.issueDocumentKeySchema = exports.issueDocumentFormatSchema = exports.createIssueAttachmentMetadataSchema = exports.linkIssueApprovalSchema = exports.addIssueCommentSchema = exports.checkoutIssueSchema = exports.issueExecutionWorkspaceSettingsSchema = exports.updateIssueSchema = exports.createIssueLabelSchema = exports.createIssueSchema = exports.projectExecutionWorkspacePolicySchema = exports.updateProjectWorkspaceSchema = exports.createProjectWorkspaceSchema = exports.updateProjectSchema = exports.createProjectSchema = exports.updateAgentPermissionsSchema = exports.agentPermissionsSchema = exports.testAdapterEnvironmentSchema = exports.resetAgentSessionSchema = exports.wakeAgentSchema = exports.createAgentKeySchema = exports.updateAgentInstructionsPathSchema = exports.updateAgentSchema = exports.createAgentHireSchema = exports.createAgentSchema = exports.companyPortabilityImportSchema = exports.companyPortabilityPreviewSchema = exports.companyPortabilityExportSchema = exports.portabilityCollisionStrategySchema = exports.portabilityAgentSelectionSchema = exports.portabilityTargetSchema = exports.portabilitySourceSchema = exports.portabilityManifestSchema = exports.portabilityAgentManifestEntrySchema = exports.portabilityCompanyManifestEntrySchema = exports.portabilitySecretRequirementSchema = exports.portabilityIncludeSchema = exports.updateCompanySchema = exports.createCompanySchema = exports.resolveBudgetIncidentSchema = exports.upsertBudgetPolicySchema = exports.patchInstanceExperimentalSettingsSchema = exports.instanceExperimentalSettingsSchema = void 0;
exports.listPluginStateSchema = exports.setPluginStateSchema = exports.pluginStateScopeKeySchema = exports.uninstallPluginSchema = exports.updatePluginStatusSchema = exports.patchPluginConfigSchema = exports.upsertPluginConfigSchema = exports.installPluginSchema = exports.pluginManifestV1Schema = exports.pluginLauncherDeclarationSchema = exports.pluginLauncherRenderDeclarationSchema = exports.pluginLauncherActionDeclarationSchema = exports.pluginUiSlotDeclarationSchema = exports.pluginToolDeclarationSchema = exports.pluginWebhookDeclarationSchema = exports.pluginJobDeclarationSchema = exports.jsonSchemaSchema = exports.updateUserCompanyAccessSchema = exports.updateMemberPermissionsSchema = exports.claimJoinRequestApiKeySchema = exports.listJoinRequestsQuerySchema = exports.acceptInviteSchema = exports.createOpenClawInvitePromptSchema = exports.createCompanyInviteSchema = exports.createAssetImageMetadataSchema = exports.createFinanceEventSchema = exports.updateBudgetSchema = exports.createCostEventSchema = exports.updateSecretSchema = exports.rotateSecretSchema = exports.createSecretSchema = exports.envConfigSchema = exports.envBindingSchema = exports.envBindingSecretRefSchema = exports.envBindingPlainSchema = exports.addApprovalCommentSchema = exports.resubmitApprovalSchema = exports.requestApprovalRevisionSchema = exports.resolveApprovalSchema = exports.createApprovalSchema = exports.updateGoalSchema = exports.createGoalSchema = exports.executionWorkspaceStatusSchema = void 0;
var instance_js_1 = require("./instance.js");
Object.defineProperty(exports, "instanceExperimentalSettingsSchema", { enumerable: true, get: function () { return instance_js_1.instanceExperimentalSettingsSchema; } });
Object.defineProperty(exports, "patchInstanceExperimentalSettingsSchema", { enumerable: true, get: function () { return instance_js_1.patchInstanceExperimentalSettingsSchema; } });
var budget_js_1 = require("./budget.js");
Object.defineProperty(exports, "upsertBudgetPolicySchema", { enumerable: true, get: function () { return budget_js_1.upsertBudgetPolicySchema; } });
Object.defineProperty(exports, "resolveBudgetIncidentSchema", { enumerable: true, get: function () { return budget_js_1.resolveBudgetIncidentSchema; } });
var company_js_1 = require("./company.js");
Object.defineProperty(exports, "createCompanySchema", { enumerable: true, get: function () { return company_js_1.createCompanySchema; } });
Object.defineProperty(exports, "updateCompanySchema", { enumerable: true, get: function () { return company_js_1.updateCompanySchema; } });
var company_portability_js_1 = require("./company-portability.js");
Object.defineProperty(exports, "portabilityIncludeSchema", { enumerable: true, get: function () { return company_portability_js_1.portabilityIncludeSchema; } });
Object.defineProperty(exports, "portabilitySecretRequirementSchema", { enumerable: true, get: function () { return company_portability_js_1.portabilitySecretRequirementSchema; } });
Object.defineProperty(exports, "portabilityCompanyManifestEntrySchema", { enumerable: true, get: function () { return company_portability_js_1.portabilityCompanyManifestEntrySchema; } });
Object.defineProperty(exports, "portabilityAgentManifestEntrySchema", { enumerable: true, get: function () { return company_portability_js_1.portabilityAgentManifestEntrySchema; } });
Object.defineProperty(exports, "portabilityManifestSchema", { enumerable: true, get: function () { return company_portability_js_1.portabilityManifestSchema; } });
Object.defineProperty(exports, "portabilitySourceSchema", { enumerable: true, get: function () { return company_portability_js_1.portabilitySourceSchema; } });
Object.defineProperty(exports, "portabilityTargetSchema", { enumerable: true, get: function () { return company_portability_js_1.portabilityTargetSchema; } });
Object.defineProperty(exports, "portabilityAgentSelectionSchema", { enumerable: true, get: function () { return company_portability_js_1.portabilityAgentSelectionSchema; } });
Object.defineProperty(exports, "portabilityCollisionStrategySchema", { enumerable: true, get: function () { return company_portability_js_1.portabilityCollisionStrategySchema; } });
Object.defineProperty(exports, "companyPortabilityExportSchema", { enumerable: true, get: function () { return company_portability_js_1.companyPortabilityExportSchema; } });
Object.defineProperty(exports, "companyPortabilityPreviewSchema", { enumerable: true, get: function () { return company_portability_js_1.companyPortabilityPreviewSchema; } });
Object.defineProperty(exports, "companyPortabilityImportSchema", { enumerable: true, get: function () { return company_portability_js_1.companyPortabilityImportSchema; } });
var agent_js_1 = require("./agent.js");
Object.defineProperty(exports, "createAgentSchema", { enumerable: true, get: function () { return agent_js_1.createAgentSchema; } });
Object.defineProperty(exports, "createAgentHireSchema", { enumerable: true, get: function () { return agent_js_1.createAgentHireSchema; } });
Object.defineProperty(exports, "updateAgentSchema", { enumerable: true, get: function () { return agent_js_1.updateAgentSchema; } });
Object.defineProperty(exports, "updateAgentInstructionsPathSchema", { enumerable: true, get: function () { return agent_js_1.updateAgentInstructionsPathSchema; } });
Object.defineProperty(exports, "createAgentKeySchema", { enumerable: true, get: function () { return agent_js_1.createAgentKeySchema; } });
Object.defineProperty(exports, "wakeAgentSchema", { enumerable: true, get: function () { return agent_js_1.wakeAgentSchema; } });
Object.defineProperty(exports, "resetAgentSessionSchema", { enumerable: true, get: function () { return agent_js_1.resetAgentSessionSchema; } });
Object.defineProperty(exports, "testAdapterEnvironmentSchema", { enumerable: true, get: function () { return agent_js_1.testAdapterEnvironmentSchema; } });
Object.defineProperty(exports, "agentPermissionsSchema", { enumerable: true, get: function () { return agent_js_1.agentPermissionsSchema; } });
Object.defineProperty(exports, "updateAgentPermissionsSchema", { enumerable: true, get: function () { return agent_js_1.updateAgentPermissionsSchema; } });
var project_js_1 = require("./project.js");
Object.defineProperty(exports, "createProjectSchema", { enumerable: true, get: function () { return project_js_1.createProjectSchema; } });
Object.defineProperty(exports, "updateProjectSchema", { enumerable: true, get: function () { return project_js_1.updateProjectSchema; } });
Object.defineProperty(exports, "createProjectWorkspaceSchema", { enumerable: true, get: function () { return project_js_1.createProjectWorkspaceSchema; } });
Object.defineProperty(exports, "updateProjectWorkspaceSchema", { enumerable: true, get: function () { return project_js_1.updateProjectWorkspaceSchema; } });
Object.defineProperty(exports, "projectExecutionWorkspacePolicySchema", { enumerable: true, get: function () { return project_js_1.projectExecutionWorkspacePolicySchema; } });
var issue_js_1 = require("./issue.js");
Object.defineProperty(exports, "createIssueSchema", { enumerable: true, get: function () { return issue_js_1.createIssueSchema; } });
Object.defineProperty(exports, "createIssueLabelSchema", { enumerable: true, get: function () { return issue_js_1.createIssueLabelSchema; } });
Object.defineProperty(exports, "updateIssueSchema", { enumerable: true, get: function () { return issue_js_1.updateIssueSchema; } });
Object.defineProperty(exports, "issueExecutionWorkspaceSettingsSchema", { enumerable: true, get: function () { return issue_js_1.issueExecutionWorkspaceSettingsSchema; } });
Object.defineProperty(exports, "checkoutIssueSchema", { enumerable: true, get: function () { return issue_js_1.checkoutIssueSchema; } });
Object.defineProperty(exports, "addIssueCommentSchema", { enumerable: true, get: function () { return issue_js_1.addIssueCommentSchema; } });
Object.defineProperty(exports, "linkIssueApprovalSchema", { enumerable: true, get: function () { return issue_js_1.linkIssueApprovalSchema; } });
Object.defineProperty(exports, "createIssueAttachmentMetadataSchema", { enumerable: true, get: function () { return issue_js_1.createIssueAttachmentMetadataSchema; } });
Object.defineProperty(exports, "issueDocumentFormatSchema", { enumerable: true, get: function () { return issue_js_1.issueDocumentFormatSchema; } });
Object.defineProperty(exports, "issueDocumentKeySchema", { enumerable: true, get: function () { return issue_js_1.issueDocumentKeySchema; } });
Object.defineProperty(exports, "upsertIssueDocumentSchema", { enumerable: true, get: function () { return issue_js_1.upsertIssueDocumentSchema; } });
var work_product_js_1 = require("./work-product.js");
Object.defineProperty(exports, "createIssueWorkProductSchema", { enumerable: true, get: function () { return work_product_js_1.createIssueWorkProductSchema; } });
Object.defineProperty(exports, "updateIssueWorkProductSchema", { enumerable: true, get: function () { return work_product_js_1.updateIssueWorkProductSchema; } });
Object.defineProperty(exports, "issueWorkProductTypeSchema", { enumerable: true, get: function () { return work_product_js_1.issueWorkProductTypeSchema; } });
Object.defineProperty(exports, "issueWorkProductStatusSchema", { enumerable: true, get: function () { return work_product_js_1.issueWorkProductStatusSchema; } });
Object.defineProperty(exports, "issueWorkProductReviewStateSchema", { enumerable: true, get: function () { return work_product_js_1.issueWorkProductReviewStateSchema; } });
var execution_workspace_js_1 = require("./execution-workspace.js");
Object.defineProperty(exports, "updateExecutionWorkspaceSchema", { enumerable: true, get: function () { return execution_workspace_js_1.updateExecutionWorkspaceSchema; } });
Object.defineProperty(exports, "executionWorkspaceStatusSchema", { enumerable: true, get: function () { return execution_workspace_js_1.executionWorkspaceStatusSchema; } });
var goal_js_1 = require("./goal.js");
Object.defineProperty(exports, "createGoalSchema", { enumerable: true, get: function () { return goal_js_1.createGoalSchema; } });
Object.defineProperty(exports, "updateGoalSchema", { enumerable: true, get: function () { return goal_js_1.updateGoalSchema; } });
var approval_js_1 = require("./approval.js");
Object.defineProperty(exports, "createApprovalSchema", { enumerable: true, get: function () { return approval_js_1.createApprovalSchema; } });
Object.defineProperty(exports, "resolveApprovalSchema", { enumerable: true, get: function () { return approval_js_1.resolveApprovalSchema; } });
Object.defineProperty(exports, "requestApprovalRevisionSchema", { enumerable: true, get: function () { return approval_js_1.requestApprovalRevisionSchema; } });
Object.defineProperty(exports, "resubmitApprovalSchema", { enumerable: true, get: function () { return approval_js_1.resubmitApprovalSchema; } });
Object.defineProperty(exports, "addApprovalCommentSchema", { enumerable: true, get: function () { return approval_js_1.addApprovalCommentSchema; } });
var secret_js_1 = require("./secret.js");
Object.defineProperty(exports, "envBindingPlainSchema", { enumerable: true, get: function () { return secret_js_1.envBindingPlainSchema; } });
Object.defineProperty(exports, "envBindingSecretRefSchema", { enumerable: true, get: function () { return secret_js_1.envBindingSecretRefSchema; } });
Object.defineProperty(exports, "envBindingSchema", { enumerable: true, get: function () { return secret_js_1.envBindingSchema; } });
Object.defineProperty(exports, "envConfigSchema", { enumerable: true, get: function () { return secret_js_1.envConfigSchema; } });
Object.defineProperty(exports, "createSecretSchema", { enumerable: true, get: function () { return secret_js_1.createSecretSchema; } });
Object.defineProperty(exports, "rotateSecretSchema", { enumerable: true, get: function () { return secret_js_1.rotateSecretSchema; } });
Object.defineProperty(exports, "updateSecretSchema", { enumerable: true, get: function () { return secret_js_1.updateSecretSchema; } });
var cost_js_1 = require("./cost.js");
Object.defineProperty(exports, "createCostEventSchema", { enumerable: true, get: function () { return cost_js_1.createCostEventSchema; } });
Object.defineProperty(exports, "updateBudgetSchema", { enumerable: true, get: function () { return cost_js_1.updateBudgetSchema; } });
var finance_js_1 = require("./finance.js");
Object.defineProperty(exports, "createFinanceEventSchema", { enumerable: true, get: function () { return finance_js_1.createFinanceEventSchema; } });
var asset_js_1 = require("./asset.js");
Object.defineProperty(exports, "createAssetImageMetadataSchema", { enumerable: true, get: function () { return asset_js_1.createAssetImageMetadataSchema; } });
var access_js_1 = require("./access.js");
Object.defineProperty(exports, "createCompanyInviteSchema", { enumerable: true, get: function () { return access_js_1.createCompanyInviteSchema; } });
Object.defineProperty(exports, "createOpenClawInvitePromptSchema", { enumerable: true, get: function () { return access_js_1.createOpenClawInvitePromptSchema; } });
Object.defineProperty(exports, "acceptInviteSchema", { enumerable: true, get: function () { return access_js_1.acceptInviteSchema; } });
Object.defineProperty(exports, "listJoinRequestsQuerySchema", { enumerable: true, get: function () { return access_js_1.listJoinRequestsQuerySchema; } });
Object.defineProperty(exports, "claimJoinRequestApiKeySchema", { enumerable: true, get: function () { return access_js_1.claimJoinRequestApiKeySchema; } });
Object.defineProperty(exports, "updateMemberPermissionsSchema", { enumerable: true, get: function () { return access_js_1.updateMemberPermissionsSchema; } });
Object.defineProperty(exports, "updateUserCompanyAccessSchema", { enumerable: true, get: function () { return access_js_1.updateUserCompanyAccessSchema; } });
var plugin_js_1 = require("./plugin.js");
Object.defineProperty(exports, "jsonSchemaSchema", { enumerable: true, get: function () { return plugin_js_1.jsonSchemaSchema; } });
Object.defineProperty(exports, "pluginJobDeclarationSchema", { enumerable: true, get: function () { return plugin_js_1.pluginJobDeclarationSchema; } });
Object.defineProperty(exports, "pluginWebhookDeclarationSchema", { enumerable: true, get: function () { return plugin_js_1.pluginWebhookDeclarationSchema; } });
Object.defineProperty(exports, "pluginToolDeclarationSchema", { enumerable: true, get: function () { return plugin_js_1.pluginToolDeclarationSchema; } });
Object.defineProperty(exports, "pluginUiSlotDeclarationSchema", { enumerable: true, get: function () { return plugin_js_1.pluginUiSlotDeclarationSchema; } });
Object.defineProperty(exports, "pluginLauncherActionDeclarationSchema", { enumerable: true, get: function () { return plugin_js_1.pluginLauncherActionDeclarationSchema; } });
Object.defineProperty(exports, "pluginLauncherRenderDeclarationSchema", { enumerable: true, get: function () { return plugin_js_1.pluginLauncherRenderDeclarationSchema; } });
Object.defineProperty(exports, "pluginLauncherDeclarationSchema", { enumerable: true, get: function () { return plugin_js_1.pluginLauncherDeclarationSchema; } });
Object.defineProperty(exports, "pluginManifestV1Schema", { enumerable: true, get: function () { return plugin_js_1.pluginManifestV1Schema; } });
Object.defineProperty(exports, "installPluginSchema", { enumerable: true, get: function () { return plugin_js_1.installPluginSchema; } });
Object.defineProperty(exports, "upsertPluginConfigSchema", { enumerable: true, get: function () { return plugin_js_1.upsertPluginConfigSchema; } });
Object.defineProperty(exports, "patchPluginConfigSchema", { enumerable: true, get: function () { return plugin_js_1.patchPluginConfigSchema; } });
Object.defineProperty(exports, "updatePluginStatusSchema", { enumerable: true, get: function () { return plugin_js_1.updatePluginStatusSchema; } });
Object.defineProperty(exports, "uninstallPluginSchema", { enumerable: true, get: function () { return plugin_js_1.uninstallPluginSchema; } });
Object.defineProperty(exports, "pluginStateScopeKeySchema", { enumerable: true, get: function () { return plugin_js_1.pluginStateScopeKeySchema; } });
Object.defineProperty(exports, "setPluginStateSchema", { enumerable: true, get: function () { return plugin_js_1.setPluginStateSchema; } });
Object.defineProperty(exports, "listPluginStateSchema", { enumerable: true, get: function () { return plugin_js_1.listPluginStateSchema; } });
